management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8086
  tomcat:
    threads:
      max: 1000


dubbo:
  # 配置服务信息
  application:
    name: order-service
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
    address: nacos://47.113.100.78:8848
    #address: nacos://192.168.43.123:8848
    #address: nacos://127.0.0.1:8848\
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: -1
    # 设置超时时间
#    host:  192.168.0.19
  consumer:
    timeout: 4000
    check: false
spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
  application:
    name: order-service
  profiles:
    active: dev
  servlet:
    multipart:
      #是否使用http上传
      enabled: true
      #最大请求文件的大小
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 100
      #获取连接时最大等待时间
      max-wait: 60000
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8

#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    #连接池最大连接数（使用负值表示没有限制）
#    lettuce:
#      pool:
#        max-active: 100
#        # 连接池中的最大空闲连接
#        max-idle: 100
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#    # 连接超时时间（毫秒）
#    timeout: 5000000

mybatis:
  #po对象的包
  type-aliases-package: cn.edu.xmu.privilege.model
  #mapper.xml所在的位置
  mapper-locations: classpath*:cn.edu.xmu.privilege.mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql

## 配置rocketmq
#rocketmq:
#  # 指定namesrv地址
#  name-server: localhost:9876
#  producer:
#    #生产者group名称
#    group: producer_group
#    #一次发送多少数量消息
#    max-message-size: 4096
#    #发送消息超时时间,默认3000
#    send-message-timeout: 3000
#    #发送消息失败重试次数，默认2
#    retry-times-when-send-async-failed: 2





